#!/bin/sh
set -eu

# Keep the QA updater rehearsal on the same verified-TLS path used for remote
# PostgreSQL. The one-run certificate is generated by qa-postgres-tls and
# copied into this disposable database volume with PostgreSQL's required mode.
install -o postgres -g postgres -m 0644 /run/nova-qa-tls/server.crt /tmp/nova-qa-server.crt
install -o postgres -g postgres -m 0600 /run/nova-qa-tls/server.key /tmp/nova-qa-server.key

exec /usr/local/bin/docker-entrypoint.sh "$@" \
  -c ssl=on \
  -c ssl_cert_file=/tmp/nova-qa-server.crt \
  -c ssl_key_file=/tmp/nova-qa-server.key
