[build]
  publish = "web"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pg", "nodemailer"]

[[plugins]]
  package = "./netlify/plugins/nova-functions"
